[build]
  command = "npm install"
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[dev]
  framework = "#static"
